#!/bin/bash
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/11和光\第十一和光丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/11和光\第十一和光丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/18英山\第十八英山丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/18英山\第十八英山丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/21東\第二十一東丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/21東\第二十一東丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/2辰巳\第二辰巳丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/2辰巳\第二辰巳丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/33東洋\第三十三東洋丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/33東洋\第三十三東洋丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/87東洋\第八十七東洋丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/87東洋\第八十七東洋丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/MARS\SUNNYMARSFileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/MARS\SUNNYMARSFileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/ひま2\ひまわり２FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/ひま2\ひまわり２FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/中春\中春丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/中春\中春丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/八菱\第八菱洋丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/八菱\第八菱洋丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/双信\双信丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/双信\双信丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/如月\如月丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/如月\如月丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昇山\昇山丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昇山\昇山丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昭建\昭建丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昭建\昭建丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昭瑞\昭瑞丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/昭瑞\昭瑞丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/清栄\清栄丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/清栄\清栄丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/立眞\立眞丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/立眞\立眞丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/筑前\筑前丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/筑前\筑前丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/興春\興春丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/興春\興春丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/豊鶴\豊鶴丸FileOut20151231.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/黒潮\黒潮丸FileOut20151230.txt
.\Program.exe C:\Users\nmri\Documents\shunsuke\nmri/data/shipLog/黒潮\黒潮丸FileOut20151231.txt
